name: EwigesWissen
options:
  bundleIdPrefix: com.ewigeswissen
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "4"

targets:
  EwigesWissen:
    type: application
    platform: iOS
    sources:
      - EwigesWissen
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        DEVELOPMENT_TEAM: 8856S4WJHW
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        PRODUCT_BUNDLE_IDENTIFIER: com.ewigeswissen.app
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    scheme:
      testTargets:
        - EwigesWissenTests

  EwigesWissenTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - EwigesWissenTests
    dependencies:
      - target: EwigesWissen
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.ewigeswissen.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/EwigesWissen.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/EwigesWissen"
        BUNDLE_LOADER: "$(TEST_HOST)"
